name: youstory-local

services:
  pb:
    build:
      context: pb
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./pb/pb_data:/pb/pb_data
      - ./pb/pb_migrations:/pb/pb_migrations
      - ./pb/pb_hooks:/pb/pb_hooks
    ports:
      - '8090:8090'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=${ENV}
    ports:
      - 3000:3000
